= Codesys Git Converter

== Limitations

- Unit Conversion, External File, RecipeManager, Trace, Trend Recording Manager, Alarm Configuration Objects are unsupported
- Library Manager, GlobalTextList, Task Configuration, Visualization Manager must exist at the root of their respective structures
- Visualization, Visualization Manager, Application, Symbol Configuration, Project Settings are stored in the codesys XML format, and will not merge correctly, so changes to these must be handled manually
- WebVisu objects are exported and imported as part of the Visualization Manager
- Global Text List is not exported or imported, but it is generated on each import, but it does not keep the language settings

== How it works
You need to have the project structe like in the test_project example, though the only nessessary files are the project folder and the git folder, and you only really need the importer and exporter scripts from the git folder.
The .gitignore file is setup to ignore the large files generated by codesys, and the project itself, so use it if you want to avoid Git large file, you must uncomment the lines in the .gitignore file to use it.

=== Exporter
You can execute the exporter script either by calling it from codesys, or by calling it from the command line, the projectToSrc.bat file is an example of how to call the exporter from the command line.
When done, the exporter script will make a backup of you project file to project_at_export, then it will export the project to the src folder.

=== Importer
You can execute the importer script either by calling it from codesys, or by calling it from the command line, the srcToProject.bat file is an example of how to call the importer from the command line.
When done, the importer script will make a backup of you project file to project_at_import, then it will import the project from the src folder.


== Troubleshooting/Reporting

The project is not completely bullet proof, and there may be error codes, this is why both the working file ecp/src.ecp, the file when exported ecp_at_export/src.ecp and the file when imported ecp_at_import/src.ecp are stored. Any errors discovered should be registered as issues in https://github.com/LyngaaMarine/codesysGit/issues

== Changelog

- *0.0.1* +
Initial Release
